name: Code Style
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: PHP CS Fixer
        uses: StephaneBour/actions-php-cs-fixer@1.0
        with:
          dir: './src'