name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['5.6', '7.4', '8.0', '8.1']
        coverage-driver: [pcov]
    name: PHP ${{ matrix.php }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: gmp
          coverage: pcov
          tools: composer:v2, infection

      - name: Install dependencies
        uses: php-actions/composer@v6

      - name: Run PHPUnit
        run: vendor/bin/phpunit
        env:
          XDEBUG_MODE: coverage